[package]
name = "minotari_ledger_wallet_comms"
version = "1.5.1-pre.0"
authors = ["The Tari Development Community"]
license = "BSD-3-Clause"
edition = "2021"

[dependencies]
tari_crypto = { workspace = true, default-features = false }
tari_utilities = { workspace = true }
tari_common = { workspace = true }
tari_common_types = { workspace = true }
tari_script = { workspace = true }

minotari_ledger_wallet_common = { workspace = true }
semver = "1.0"
borsh = "1.2"
dialoguer = { version = "0.11" }
ledger-transport = { git = "https://github.com/Zondax/ledger-rs", rev = "20e2a20" }
ledger-transport-hid = { git = "https://github.com/Zondax/ledger-rs", rev = "20e2a20" }
log = "0.4.20"
once_cell = "1.19.0"
rand = "0.8"
serde = { version = "1.0.106", features = ["derive"] }
thiserror = "1.0.26"
