[package]
name = "tari_core-fuzz"
version = "0.0.0"
publish = false
edition = "2018"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
borsh = { version = "0.9.3", features = ["const-generics"] }
prost = "0.9"

[dependencies.tari_core]
path = ".."
features = ["base_node","base_node_proto"]

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[profile.release]
debug = 1

[[bin]]
name = "fuzz_target_1"
path = "fuzz_targets/fuzz_target_1.rs"
test = false
doc = false
