[package]
name = "tari_integration_tests"
authors = ["The Tari Development Community"]
repository = "https://github.com/tari-project/tari"
license = "BSD-3-Clause"
version = "0.35.1"
edition = "2018"

[dependencies]
tari_app_utilities = { path = "../applications/tari_app_utilities" }
tari_app_grpc = { path = "../applications/tari_app_grpc" }
tari_base_node_grpc_client = { path = "../clients/rust/base_node_grpc_client" }
tari_wallet_grpc_client = { path = "../clients/rust/wallet_grpc_client" }
tari_core = { path = "../base_layer/core" }
tari_common = { path = "../common" }
tari_comms = { path = "../comms/core" }
tari_comms_dht = { path = "../comms/dht" }
tari_p2p = { path = "../base_layer/p2p" }
tari_test_utils = { path = "../infrastructure/test_utils" }
tari_base_node = { path = "../applications/tari_base_node" }
tari_console_wallet = { path = "../applications/tari_console_wallet" }
tari_wallet = { path = "../base_layer/wallet" }
tari_common_types = { path = "../base_layer/common_types" }

anyhow = "1.0.53"
async-trait = "0.1.50"
axum = "0.6.0"
axum-jrpc = { version = "0.3.2", features = ["anyhow_error"] }
bincode = "1.3.3"
blake2 = "0.9.2"
borsh = { version = "0.9.3", default-features = false }
bytes = "1"
chrono = "0.4.22"
clap = { version = "3.2.5", features = ["env"] }
config = "0.13.0"
digest = "0.9.0"
diesel = { version = "1.4.8", default-features = false, features = ["sqlite"] }
futures = { version = "^0.3.1" }
json5 = "0.2.2"
include_dir = "0.7.2"
log = { version = "0.4.8", features = ["std"] }
log4rs = { version = "1.1.1", features = ["rolling_file_appender", "compound_policy", "size_trigger", "fixed_window_roller"] }
lmdb-zero = "0.4.4"
libsqlite3-sys = { version = "0.22.2", features = ["bundled"] }
prost = "0.9"
rand = "0.7"
reqwest = "0.11.11"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
time = "0.3.15"
thiserror = "^1.0.20"
tokio = { version = "1.10", features = ["macros", "time", "sync", "rt-multi-thread"] }
tokio-stream = { version = "0.1.7", features = ["sync"] }
tonic = "0.6.2"
tower = "0.4"
tower-layer = "0.3"
tower-http = { version = "0.3.0", features = ["cors"] }


[dev-dependencies]
tari_crypto = { git = "https://github.com/tari-project/tari-crypto.git", tag = "v0.16.5" }

# FIXME: the newest version failed compilation due to a missing "bool_to_option" unstable feature
#cucumber = { version = "0.13.0", features = ["default"] }
cucumber = { version = "0.18.0", features = ["default", "libtest"] }
tempfile = "3.3.0"
indexmap = "1.9.1"

[[test]]
name = "cucumber" # this should be the same as the filename of your test target
harness = false # allows Cucumber to print output instead of libtest
