[advisories]
ignore = [
    # All data structures using borsh ser/de have been reviewed for ZST's and we have found no reason for concern.
    # TODO: Remove this line after borsh-rs has been upgraded to >=0.12.0
    # https://github.com/near/borsh-rs/pull/146
    "RUSTSEC-2023-0033",
]
