[package]
name = "tari_base_layer_proto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.9"
prost-types = "0.9"

[build-dependencies]
tari_common = { version = "^0.38", path = "../../common", features = ["build"] }
